#!/bin/sh
# Ce script permet d'installer tous les scripts et fichiers de config
printf "Êtes-vous sûr de vouloir installer cette config ?\nVos fichiers seront re-écrits. [o/N]"
read choise
if [ "$choise" = "o" ]; then
	sh dep-install
	cp -r .config ~/
    cp -r .local ~/
	cp .xinitrc .zshenv ~/
	cd ~/.config/dmenu
	sudo make clean install
	cd ../dwm
	sudo make clean install
	cd ../dwmblocks
	sudo make clean install
	cd
	chsh -s /bin/zsh $(whoami)
	sudo ln -sfT dash /usr/bin/sh
        git clone https://github.com/lukesmithxyz/st
        cd st
        sudo make clean install
	sudo git clone https://github.com/zdharma/fast-syntax-highlighting /usr/share/zsh/plugins/fsh
	exit 1
fi
echo "Opération annulée."
exit 1
