#!/bin/sh
# Ce script permet d'installer tous les scripts et fichiers de config
echo "Pensez d'abord à installer les dépendances avant de copier les fichiers de config."
printf "Êtes-vous sûr de vouloir installer cette config ?\nVos fichiers seront re-écrits. [o/N]"
read -r choise
if [ "$choise" = "o" ]; then
    cp -r .config ~/
    cp -r .local/ ~/
    sudo cp -r etc /etc
    sudo cp -r usr/share /usr/share
    cp .zshenv ~/
    cd ~/.config/dmenu || exit
    sudo make clean install
    cd ../dwm || exit
    sudo make clean install
    cd ../dwmblocks || exit
    sudo make clean install
    cd ../surf || exit
    sudo make clean install
    cd ~ || exit
    chsh -s /bin/fish "$(whoami)"
    sudo ln -sfT dash /bin/sh
    git clone https://github.com/lukesmithxyz/st
    cd st || exit
    sudo make clean install
    systemctl --user enable --now gnome-keyring-daemon
else
    echo "Opération annulée."
fi
