abbr --position anywhere --add dp --set-cursor '~/Documents/prog/%'
abbr --position anywhere --add dpp --set-cursor '~/Documents/prog/python/%'
abbr --position anywhere --add dps --set-cursor '~/Documents/prog/shell/%'
abbr --position anywhere --add dt --set-cursor '~/Documents/torrent/%'
abbr --position anywhere --add dm --set-cursor '~/Documents/media/%'
abbr --position anywhere --add vid --set-cursor '~/Videos/%'
abbr --position anywhere --add pic --set-cursor '~/Pictures/%'
abbr --position anywhere --add .c --set-cursor '~/.config/%'
abbr --position anywhere --add .ca --set-cursor '~/.config/alacritty/%'
abbr --position anywhere --add .cf --set-cursor '~/.config/fish/%'
abbr --position anywhere --add .cs --set-cursor '~/.config/sway/%'

abbr --position command --add ssa 'sudo systemctl start'
abbr --position command --add sso 'sudo systemctl stop'
abbr --position command --add ssd 'sudo systemctl disable --now'
abbr --position command --add sse 'sudo systemctl enable --now'
abbr --position command --add sss 'sudo systemctl status'
abbr --position command --add sua 'systemctl --user start'
abbr --position command --add suo 'systemctl --user stop'
abbr --position command --add sud 'systemctl --user disable --now'
abbr --position command --add sue 'systemctl --user enable --now'
abbr --position command --add sus 'systemctl --user status'

abbr --position anywhere --add L --set-cursor '% | less'
abbr --position command --add s 'sudo'
