alias ls "exa -l --git"
alias la "exa -l --git -a"
alias l "exa -l --git"
alias ms "exa -l --git"
alias p "sudo pacman --color=always"
alias y "yay"
alias v "nvim"
alias vim "nvim"
alias sxiv "sxiv -g 640x480 "
alias mkdir "mkdir -p"
alias m "mkdir -p"
alias rm "rm -rf"
alias cp "cp -r"
alias ga "git add"
alias gm "git commit"
alias gpom "git push origin main"
alias s "sxiv"
alias cat "bat"
alias za "zathura"
alias lf "lfrun"
alias py "python"
alias ip "ip -c"
alias grep "grep --color=auto"
alias xo "xdg-open"
