#!/bin/sh
alias ls="exa"
alias la="exa -a"
alias l="exa"
alias ms="exa"
alias ytv="youtube-viewer"
alias z="zathura"
alias p="pacman"
alias y="yay"
alias v="nvim"
alias vim="nvim"
alias zsource="source ~/.config/zsh/.zshrc"
alias sxiv="sxiv -g 640x480 "
alias mkdir="mkdir -p"
alias md="mkdir -p"
alias m="mkdir -p"
alias rm="rm -rf"
alias ga="git add"
alias gm="git commit"
alias gpom="git push origin main"

for command in mount umount sv pacman updatedb su shutdown poweroff reboot ; do
	alias $command="sudo $command"
done; unset command
