import = ["/home/antonin/.config/alacritty/exylos3.toml"]

[env]
TERM = "alacritty"

[font]
size = 11.2

[[keyboard.bindings]]
action = "Paste"
key = "V"
mode = "~Vi"
mods = "Alt"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Alt"

[shell]
args = ["-l", "-c", "tmux attach || tmux"]
program = "/bin/fish"

[window]
opacity = 0.8

[window.padding]
x = 5
y = 5
