[colors.bright]
black = "#686f9a"
blue = "#11b4dd"
cyan = "#8b6ddd"
green = "#6ddda7"
magenta = "#c4b2f7"
red = "#f44511"
white = "#f0f1ce"
yellow = "#ffee00"

[colors.normal]
black = "#000000"
blue = "#00a3cc"
cyan = "#7a5ccc"
green = "#5ccc96"
magenta = "#b3a1e6"
red = "#e33400"
white = "#686f9a"
yellow = "#f2ce00"

[colors.primary]
background = "#000000"
foreground = "#ecf0c1"
