#!/bin/sh
cp sudoers /etc/
cp mirrorlist-arch /etc/pacman.d/
cp pacman.conf /etc/
cp locale.gen /etc/
locale-gen
#paquets à installer pour une installation basique
sudo pacman -Syu
sudo pacman -S networkmanager networkmanager-runit grub efibootmgr awk
#clavier
echo "KEYMAP=fr" > /etc/vconsole.conf
#langue
echo "LANG=fr_FR.UTF-8" > /etc/locale.conf
#grub
architect=$(lscpu | head -1 | awk '{print $2}')
grub-install --target="$architect" /dev/sda
grub-mkconfig -o /boot/grub/grub.cfg
#le réseau
ln -s /etc/runit/sv/NetworkManager /etc/runit/runsvdir/default
#horloge
ln -sf /usr/share/zoneinfo/Europe/Paris /etc/localtime
#config mot de passe et nom d'utilisateur
printf "mot de passe de root : "
passwd
set -f
printf "nom de l'utilisateur à créer : "
read ans
useradd -mg wheel "$ans"
printf "mot de passe de %s : \n" "$ans"
passwd "$ans"
printf "script terminé."
